baseURL = "https://paraphrased.github.io/"
languageCode = "en-us"
title = "Paraphrasing Parables"
theme = "ezhil"


# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "yet another blog seeking internet validation"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    #featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/favicon.ico"

    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode
    mode = "auto" # "dark" or "auto"

# Main menu which appears below site header.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).

# [[params.social]]
#     name = "Github"
#     icon = "github"
#     url = "https://github.com/arnobbhanja"
# 
# [[params.social]]
#     name = "Linkedin"
#     icon = "linkedin"
#     url = "https://linkedin.com/in/arnobbhanja"
# 
# [[params.social]]
#     name = "Twitter"
#     icon = "twitter"
#     url = "https://twitter.com/lookingfence"

# Enable tags.
[taxonomies]
   tag = "tags"
